### PR TITLE
Initial profiling/benchmarking functions

### PR DESCRIPTION
**Pull request by TimGuiteDiamond**
Hopefully will help us to understand where the bottlenecks are in the system and how the performance of coniql (or indeed other servers) changes with respect tothe data being requested.

### CODE REVIEW

**Comment by TimGuiteDiamond** [comment]
@willrogers see benchmarking efforts here, more work to be done but a good start I think

**Comment by TimGuiteDiamond** [comment]
Results of initial performance benchmarking, using `PUT` requests:

----- Sine Wave of size 1 -----
Measured 100 times:
Shortest time:  7.494688 ms
Longest time:   26.759148 ms
Mean time:      8.370655 ms
Median time:    8.370655 ms
----- Sine Wave of size 10 -----
Measured 100 times:
Shortest time:  7.498503 ms
Longest time:   10.499239 ms
Mean time:      8.022254 ms
Median time:    8.022254 ms
----- Sine Wave of size 100 -----
Measured 100 times:
Shortest time:  7.471561 ms
Longest time:   9.472370 ms
Mean time:      7.895296 ms
Median time:    7.895296 ms
----- Sine Wave of size 1000 -----
Measured 100 times:
Shortest time:  7.621527 ms
Longest time:   9.611130 ms
Mean time:      8.063924 ms
Median time:    8.063924 ms
----- Sine Wave of size 10000 -----
Measured 100 times:
Shortest time:  8.728981 ms
Longest time:   11.934519 ms
Mean time:      9.141057 ms
Median time:    9.141057 ms
----- Sine Wave of size 100000 -----
Measured 100 times:
Shortest time:  17.759562 ms
Longest time:   30.980825 ms
Mean time:      18.795810 ms
Median time:    18.795810 ms
----- Sine Wave of size 1000000 -----
Measured 100 times:
Shortest time:  107.100964 ms
Longest time:   238.528490 ms
Mean time:      134.630988 ms
Median time:    134.630988 ms
----- Sine Wave of size 10000000 -----
Measured 100 times:
Shortest time:  1450.248957 ms
Longest time:   2658.150673 ms
Mean time:      2058.262234 ms
Median time:    2058.262234 ms

**Notable:** Over a second for waveforms with 10^7 elements! Pretty stable up to 10000 elements.

@willrogers

**Comment by TimGuiteDiamond** [comment]
Following a chat with @thomascobb there are now a few interesting avenues to investigate:

- what is the performance of the graphql schema itself? This will remove the connection part of the equation
- how does performance change if we make a full web socket based connection to a graphql subscription?
  - what happens when the data is big?
  - what happens when the number of subscribers (connections) is big?

I will seek to inve

**Comment by TimGuiteDiamond** [comment]
Results found using `server_performance.py` which is hopefully a good indication of the query performance:

```
----- Sine value -----
Measured 100 times:
Shortest time:  4.856348 ms
Longest time:   13.866901 ms
Mean time:      5.200865 ms
Median time:    5.200865 ms
----- Sine Wave of size 1 -----
Measured 100 times:
Shortest time:  4.900217 ms
Longest time:   6.607294 ms
Mean time:      5.117660 ms
Median time:    5.117660 ms
----- Sine Wave of size 10 -----
Measured 100 times:
Shortest time:  4.889488 ms
Longest time:   5.956888 ms
Mean time:      5.086491 ms
Median time:    5.086491 ms
----- Sine Wave of size 100 -----
Measured 100 times:
Shortest time:  4.916906 ms
Longest time:   6.172180 ms
Mean time:      5.119154 ms
Median time:    5.119154 ms
----- Sine Wave of size 1000 -----
Measured 100 times:
Shortest time:  4.857063 ms
Longest time:   6.281376 ms
Mean time:      5.120642 ms
Median time:    5.120642 ms
----- Sine Wave of size 10000 -----
Measured 100 times:
Shortest time:  5.009651 ms
Longest time:   7.729530 ms
Mean time:      5.194623 ms
Median time:    5.194623 ms
----- Sine Wave of size 100000 -----
Measured 100 times:
Shortest time:  7.090807 ms
Longest time:   22.054911 ms
Mean time:      7.491837 ms
Median time:    7.491837 ms
----- Sine Wave of size 1000000 -----
Measured 100 times:
Shortest time:  28.219223 ms
Longest time:   166.321754 ms
Mean time:      30.300059 ms
Median time:    30.300059 ms
----- Sine Wave of size 10000000 -----
Measured 100 times:
Shortest time:  273.162842 ms
Longest time:   1655.036449 ms
Mean time:      333.300529 ms
Median time:    333.300529 ms
```

**Notes:** I had to run this without the validation for the 10^7 case as it was taking too long, which suggest there is a significant cost to decoding arrays of this size. Running with the validation for the other sizes suggests the correct data was being received.

**Comment by TimGuiteDiamond** [comment]
Slowdown on the shortest time for the `PUT` requests, largest vs shortest: 1450.25 / 7.49 = 193.6
Slowdown on the shortest time for the queries, largest vs shortest: 273.16 / 4.90 = 55.7

This suggests the slowdown grows more quickly on the network but both show significant slowdown as array size increases, especially above 10^4 elements

**Comment by TimGuiteDiamond** [comment]
@thomascobb I think the performance test is measuring what I want to test, but I am not particularly experienced with this framework, so if you have any comments, suggestions or corrections please share them :smiley:

**Comment by TimGuiteDiamond** [comment]
Arrays which are to be sent out from coniql travel through the `serialize_any` function:

```python
def serialize_any(value):
    if isinstance(value, ArrayWrapper):
        return dict(
            numberType=value.array.dtype.name.upper(),
            # https://stackoverflow.com/a/6485943
            base64=base64.b64encode(value.array).decode()
        )
    elif dataclasses.is_dataclass(value):
        return dataclasses.asdict(value)
    else:
        return value
```

The `.decode()` after base 64 encoding turns the byte array into a string. This explains why it is necessary to *encode* the string in order to base64 decode it:

```python
>>> import base64
>>> import numpy as np
>>> x = np.array([0, 1, 2, 3, 4, 5])
>>> base64.b64encode(x)
b'AAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAA'
>>> base64.b64encode(x).decode()
'AAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAA'
```

I guess this could be slowing down the query response somewhat in the above test but presumably it would have to be done at some point before sending over web socket anyway?

@thomascobb I will try and find a suitable profiler to investigate the performance metrics of various parts of this process.

**Comment by TimGuiteDiamond** [comment]
Extracted "initial" load as it's own metric; as predicted, for the large loads this is the longest time:

```
----- Sine Wave of size 1 -----
Measured 100 times:
Initial time:   1.800537 ms
Shortest time:  1.465082 ms
Longest time:   1.947880 ms
Mean time:      1.521087 ms
Median time:    1.486421 ms
----- Sine Wave of size 10 -----
Measured 100 times:
Initial time:   1.585245 ms
Shortest time:  1.463652 ms
Longest time:   1.918793 ms
Mean time:      1.505396 ms
Median time:    1.482725 ms
----- Sine Wave of size 100 -----
Measured 100 times:
Initial time:   1.744747 ms
Shortest time:  1.479149 ms
Longest time:   2.061367 ms
Mean time:      1.718054 ms
Median time:    1.663089 ms
----- Sine Wave of size 1000 -----
Measured 100 times:
Initial time:   2.130270 ms
Shortest time:  1.480103 ms
Longest time:   2.182722 ms
Mean time:      1.586795 ms
Median time:    1.507998 ms
----- Sine Wave of size 10000 -----
Measured 100 times:
Initial time:   3.108025 ms
Shortest time:  1.632452 ms
Longest time:   3.108025 ms
Mean time:      1.714976 ms
Median time:    1.660943 ms
----- Sine Wave of size 100000 -----
Measured 100 times:
Initial time:   17.156839 ms
Shortest time:  3.645897 ms
Longest time:   17.156839 ms
Mean time:      3.904331 ms
Median time:    3.706932 ms
----- Sine Wave of size 1000000 -----
Measured 100 times:
Initial time:   142.792702 ms
Shortest time:  19.356728 ms
Longest time:   142.792702 ms
Mean time:      25.612633 ms
Median time:    24.932861 ms
----- Sine Wave of size 10000000 -----
Measured 100 times:
Initial time:   1566.228628 ms
Shortest time:  279.954195 ms
Longest time:   1566.228628 ms
Mean time:      334.670110 ms
Median time:    282.585025 ms
```

There is still a **>10X** slow down moving from 10e6 to 10e7 values

**Comment by TimGuiteDiamond** [comment]
I have performed some testing involving clients which subscribe using the web socket interface, with an increasing number of subscriptions.

The table below shows the rate at which messages were received from the subscriptions when the simulation values were given an `update_time` of 0.1s, 10 Hz.

| Subscriptions | Sine Scalar (Hz) | Sinewave of 1 (Hz) | Sinewave of 10 (Hz) | Sinewave of 100 (Hz) |
|---------------|------------------|--------------------|---------------------|----------------------|
| 10            | 10.01            | 10.05              | 10.03               | 10.01                |
| 20            | 10.00            | 10.02              | 10.03               | 10.01                |
| 30            | 10.10            | 10.03              | 10.01               | 10.03                |
| 40            | 10.01            | 10.01              | 10.02               | 10.06                |
| 50            | 10.00            | 9.98               | 10.02               | 10.05                |
| 60            | 10.03            | 10.02              | 10.03               | 10.02                |
| 70            | 10.07            | 10.02              | 10.00               | 10.02                |
| 80            | 10.02            | 9.98               | 9.99                | 9.99                 |
| 90            | 10.03            | 10.00              | 10.02               | 10.04                |
| 100           | 9.99             | 9.95               | 10.01               | 10.04                |
| 200           | 10.02            | 9.97               | 10.04               | 10.02                |
| 300           | 10.01            | 10.02              | 10.02               | 4.35                 |
| 400           | 10.06            | 10.05              | 10.05               | 1.30                 |
| 500           | 9.29             | 9.31               | 9.23                | 0.93                 |
| 600           | 7.74             | 7.49               | 7.54                | 0.93                 |
| 700           | 6.54             | 6.26               | 6.42                | 0.49                 |
| 800           | 5.70             | 5.37               | 5.63                | 0.09                 |
| 900           | 5.15             | 4.67               | 4.88                | 0.00                 |

## Apparent Limit

It appears that the server is hitting it's limit at 5000 messages per second - `500 subscriptions x 10 updates per second`.
This is sustained across the scalar value and wave forms of size 1 and 10.
This equates to approximately 2ms per message, which is not much above the 1.5ms measured above just for fetching the data.
Perhaps it is reasonable for the wrapping of this data into JSON and transmission to add less than 1ms.

## Big Waveforms "Completing"

You will notice that the waveform of size 100 drops at 300 subscriptions and then decreases to nothing quite quickly.
This is not an accurate measurement of the data rate being achieved, but is reflective of the server sending a `GQL_COMPLETE` message and prompting the client to stop reading messages prematurely.
The `GQL_COMPLETE` message is described briefly [here](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_complete) as part of the GraphQL web socket specification/protocol.
It appears that this message really is being received by the client, but it is not clear to me why the server is sending it. @thomascobb any ideas?

**Comment by TimGuiteDiamond** [comment]
Discussed with @thomascobb, the server CPU usage is at 99% when running the failing tests, and this is triggering a failure deep in the heart of `aiohttp`.

This will require profiling to understand what is causing the usage to rise so high.

**Comment by TimGuiteDiamond** [comment]
I have been investigating this area further in the last few weeks, as I was not entirely convinced that the measurements were indicative of the maximum server load, and might be due to the client reaching it's maximum throughput, thereby providing an upper limit on the rate which could be measured.

Indeed, it appears that despite improvements to `py-graphql-client`, it still has some intrinsic properties which reduce the maximum throughput it can measure (this might be due to the threading model it uses).

Alternative client implementations were developed using the [graphqurl](https://github.com/hasura/graphqurl) package for node.js and [websockets](https://pypi.org/project/websockets/) in Python.

The following table shows the frequency rate of subscriptions to sinewaves of increasing size in the three different implementations (averaged over 3 runs, approx. 100 reads at requested frequency of 10 Hz): 

| Size (Elements) | py-graphql-client (Hz) | JS (Hz) | websockets (Hz) |
| ------------- |-------------| -----| ------|
| 1000 | 10.0  | 10.0  | 10.0  |
| 10000 |  10.0 |  10.0 |  10.0 |
| 100000 |  2.5 |  10.0 |  10.0 |
| 1000000 | 0  | 3.6  | 2.8  |

This clearly demonstarates that our clients have different performance characteristics, and now that we know that we should be sceptical of our measurements.

The slowdown for the JS and websockets implementations takes place between 10e5 and 10e6 elements so tests were focussed in this area.

In order to verify that we are getting messages of the expected size through with valid values, verification functions have been implemented which load the JSON string into an object of some kind, decode the base64 string into an array of floating point values, and then verify that the values in this array are equal to a precomputed set of values. To make the point clear, there are three computational steps which we might expect to have an impact on the measured message rate:

- loading the JSON string into an object
- decoding the base64 encoded array into an array
- verifying the content of the array

Let us start by comparing the measurements when all three of these steps are implemented, as this will give us the highest level of confidence in the data transfer (commit c93c11):


| Size (Elements) | JS (Hz) | websockets (Hz) |
| ------------- |-----| ------|
| 1e5 | 9.99| 10.03 |
| 2e5 | 9.94 | 10.00 |
| 3e5 | 6.46 | 9.63 |
| 4e5 | 4.69  | 7.06 |
| 5e5 | 3.59 | 5.80 |
| 6e5 | 2.63 | 4.80 |
| 7e5 |2.18  | 3.80 |
| 8e5 | 1.89 | 3.42 |
| 9e5 | 1.68 | 3.01 |
| 1e6 | 1.48 | 2.80 |

The performance here is actually quite comparable, which is good as it suggests both clients are seeing the same bottlenecks.

Next, lets remove the verification step. We are still going to load the JSON string into an object and decode the base64 array (commit 5a74df):

| Size (Elements) | JS (Hz) | websockets (Hz) |
| ------------- |-----| ------|
| 1E+05 | 10.00 | 10.06 |
| 2E+05 | 9.96  | 10.02 |
| 3E+05 | 9.90  | 10.00 |
| 4E+05 | 8.66  | 9.98  |
| 5E+05 | 7.03  | 9.97  |
| 6E+05 | 5.96  | 9.96  |
| 7E+05 | 5.19  | 9.94  |
| 8E+05 | 4.59  | 9.93  |
| 9E+05 | 3.97  | 9.91  |
| 1E+06 | 3.60  | 9.89  |
 
Interestingly, and perhaps unexpectedly, we now see the measurements diverge quite significantly! It appears that the Python client was facing a bottleneck during the verification step and can now run much more quickly. Although performance does decrease, it is now at a seemingly linear rate and not seeing the kind of drop off we saw before, or continue to see in the JS client. The JS client hangs on for a little longer than before but still sees a distinct drop in performance.

We can also remove the base64 decoding step (commit 251260):

| Size (Elements) | JS (Hz) | websockets (Hz) |
| ------------- |-----| ------|
| 1E+05 | 10.00 | 10.06 |
| 2E+05 | 9.93  | 10.04 |
| 3E+05 | 9.90  | 10.01 |
| 4E+05 | 8.63  | 10.01 |
| 5E+05 | 7.00  | 9.98  |
| 6E+05 | 5.99  | 9.97  |
| 7E+05 | 5.13  | 9.96  |
| 8E+05 | 4.57  | 9.94  |
| 9E+05 | 4.10  | 9.93  |
| 1E+06 | 3.70  | 9.90  |

Here we see very similar results as in the previous step, which suggests that the base64 decoding is fairly efficient, or at the least is not an obvious bottleneck.

Due to the the JS client is structured, it is not immediately obvious (to the author) how to remove the loading step, but we can do it for the Python client, and extend the size of waveforms we are looking at, having previously seen the slow decrease below 1e6 (commit 7d3b42):

| Size (Elements) | websockets (Hz) |
| ------------- |-----|
| 1E+06 | 9.92 |
| 2E+06 | 8.20 |
| 3E+06 | 5.04 |
| 4E+06 | 3.02 |

Here we see that there is finally a distinct drop off at around 2e6 elements. You might be wondering what happens when we ask for a waveform of 5e6 elements (the exact limit is a bit variable):

```bash
# On the client
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 8000, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8000)

# On the server
Killed
``` 

So perhaps we have finally reached the approximate limit of the server? @thomascobb I am not exactly sure why this happens.

# Future work

- Run the client and server on different machines and see if this has any effect on performance
- Apply similar benchmarking techniques to the server changes here: #4 
  - We would expect to see better server performance, so if we don't then that would be another piece of evidence that the client side is limiting measurement capabilities
- Test for many small subscriptions vs few big subscriptions
  - How does metadata and other setup costs of maintaining different subscriptions compare to large waveforms?

@thomascobb @willrogers I would be interested in some feedback on this work and the benchmarking code I have written so far. I think it can certainly be distilled and ideally the JS client and Python client would be very similarly structured to allow for cleaner comparisons.

**Comment by thomascobb** [comment]
Work moved to #5

**Pull request closed without merging**
