### PR TITLE
Benchmarking Tartiflette

### PR DESCRIPTION
**Pull request by TimGuiteDiamond**
Attempting to implement same tests as on #3 but for the proposed changes via #4

### CODE REVIEW

**Comment by TimGuiteDiamond** [comment]
Currently facing issue with possible throttling or messages not being recieved?

On the client, print out every time `SineWaveSimple` is updated:

```
$ pipenv run python -m coniql
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
[9. 0. 1. 2. 3. 4. 5. 6. 7. 8.]
[8. 9. 0. 1. 2. 3. 4. 5. 6. 7.]
[7. 8. 9. 0. 1. 2. 3. 4. 5. 6.]
[6. 7. 8. 9. 0. 1. 2. 3. 4. 5.]
[5. 6. 7. 8. 9. 0. 1. 2. 3. 4.]
[4. 5. 6. 7. 8. 9. 0. 1. 2. 3.]
[3. 4. 5. 6. 7. 8. 9. 0. 1. 2.]
[2. 3. 4. 5. 6. 7. 8. 9. 0. 1.]
[1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
```

On the client, decode the base64 array and print it out:

```
$ pipenv run python benchmark/asyncClient.py 
--- sim://sinewavesimple ---
--- Size: 10, Update Time: 0.1 s, Messages to test: 100, ---
Connected...
[9. 0. 1. 2. 3. 4. 5. 6. 7. 8.]
[7. 8. 9. 0. 1. 2. 3. 4. 5. 6.]
[5. 6. 7. 8. 9. 0. 1. 2. 3. 4.]
[3. 4. 5. 6. 7. 8. 9. 0. 1. 2.]
[1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
[9. 0. 1. 2. 3. 4. 5. 6. 7. 8.]
[7. 8. 9. 0. 1. 2. 3. 4. 5. 6.]
[5. 6. 7. 8. 9. 0. 1. 2. 3. 4.]
[3. 4. 5. 6. 7. 8. 9. 0. 1. 2.]
[1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
```

Only every second message is getting through? This appears to remain the case regardless of `update_time`.

@thomascobb I will investigate but wondering if you know where this is coming from and could save me some time?

**Comment by TimGuiteDiamond** [comment]
Issue fixed, was a result of too many `await.recv()` calls during quick modifications

**Comment by TimGuiteDiamond** [comment]
Interestingly, my initial tests have yielded almost exactly the same results as demonstrated on #3 !

This suggests (to me) that the limit is on the client side in terms of measuring the performance, as I would expect to see different performance characteristics between the two server implementations.

Further investigation is required:

- what is causing the bottlenecks on the client side? Is it I/O bound?
- can we stretch the performance of the server by applying many subscriptions at once?

**Comment by TimGuiteDiamond** [comment]
@thomascobb I have removed the redundant Python scripts and merged in the latest master with according changes. Should be ready to merge.

**Comment by thomascobb** [comment]
This works for me now, please could you put some instructions about how you install and run up the javascript benchmarking in a README file in the benchmarks directory, or as a benchmarking.rst file in the docs directory?

**Comment by TimGuiteDiamond** [comment]
Yep will write some documentation this afternoon 👍

**Comment by TimGuiteDiamond** [comment]
@thomascobb Have added a page in docs. Let me know if you think I should go into more detail.

**Pull request merged**
